### ISSUE TITLE
[HW] <K S A R AMBEDKAR>

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-introduction-to-nosql#32] opened 2021-05-10 15:45 UTC
**Name:** K S A R AMBEDKAR
**Email:** <ambedkar1985@gmail.com
[HW Assignment of Introduction to NoSQL Databases.pdf](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6453288/HW.Assignment.of.Introduction.to.NoSQL.Databases.pdf)
>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment] 2021-05-13 14:02
Looks good, thank you.

**Comment by HadesArchitect** [comment] 2021-05-17 14:03
Duplicate of #27

**Closed by HadesArchitect** 2021-05-17 14:03 UTC
Labels: accepted, duplicate, homework
