### ISSUE TITLE
[HW] <bathini sowjanya>

### ISSUE THREAD

**Issue by bathinisowjanya** [datastaxdevs/workshop-introduction-to-nosql#59] opened 2021-05-20 15:16 UTC
**Name:** <bathini sowjanya>
**Email:** <sowjanyamudhiraj55@gmail.com>
**Linkedin Profile:** **<https://www.linkedin.com/in/bathini-sowjanya-56b6351a0/>**

Attach the homework screenshots below:
-----------------------------------------
![WhatsApp Image 2021-05-20 at 8 44 05 PM (5)](https://user-images.githubusercontent.com/84471497/119004556-4c447380-b9ac-11eb-9947-fcf9ba962e44.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM (4)](https://user-images.githubusercontent.com/84471497/119004566-4ea6cd80-b9ac-11eb-8c0e-925744362f1c.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM (3)](https://user-images.githubusercontent.com/84471497/119004582-51a1be00-b9ac-11eb-9beb-409a08638d71.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM (2)](https://user-images.githubusercontent.com/84471497/119004589-536b8180-b9ac-11eb-9406-a44203583351.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM (1)](https://user-images.githubusercontent.com/84471497/119004600-549cae80-b9ac-11eb-9e1a-3c1d1457b945.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM](https://user-images.githubusercontent.com/84471497/119004612-56667200-b9ac-11eb-8670-863a2b9ee410.jpeg)
![WhatsApp Image 2021-05-20 at 8 44 05 PM (5)](https://user-images.githubusercontent.com/84471497/119004779-7d24a880-b9ac-11eb-8da7-f585b5f2b0d4.jpeg)

<SCREENSHOTS>

**Comment by SonicDMG** [comment] 2021-05-21 12:42
Hey Bathini, thanks for the submission. Looks good other than missing the "try-it-scenario" from step 2 of the homework.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete that scenario and provide a screenshot. :)

**Comment by SonicDMG** [comment] 2021-05-21 12:45
Duplicate of https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/61, closing.

**Closed by SonicDMG** 2021-05-21 12:45 UTC
Labels: homework, needs improvement
