### ISSUE TITLE
[HW] <Shiva Farkade>

### ISSUE THREAD

**Issue by shivafarkade1889** [datastaxdevs/workshop-introduction-to-nosql#34] opened 2021-05-13 10:28 UTC
**Name:** <Shiva Farkade>
**Email:** <shivafarkade@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shiva-farkade/>

Attach the homework screenshots below:
-----------------------------------------
[Astra-HomeWork-Shiva Farkade.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6471880/Astra-HomeWork-Shiva.Farkade.docx)
[HomeWork-Shiva Farkade - 5.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6471883/HomeWork-Shiva.Farkade.-.5.docx)

![image](https://user-images.githubusercontent.com/68903482/118113411-e5e7b000-b403-11eb-8711-b167aecb54f7.png)
![image](https://user-images.githubusercontent.com/68903482/118113351-ccdeff00-b403-11eb-974a-feed46492923.png)
![image](https://user-images.githubusercontent.com/68903482/118113364-d2d4e000-b403-11eb-9ce8-3895ab0ee91b.png)
![image](https://user-images.githubusercontent.com/68903482/118113371-d5373a00-b403-11eb-84d5-045683c12960.png)

**Comment by SonicDMG** [comment] 2021-05-13 13:38
Looks good Shiva. Nice job getting through the graph portion as well. Thank you.

**Comment by HadesArchitect** [comment] 2021-05-14 12:17
Duplicate of #11

**Closed by HadesArchitect** 2021-05-14 12:17 UTC
Labels: accepted, homework
