### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by narviksz** [datastaxdevs/workshop-introduction-to-nosql#564] opened 2021-09-02 06:37 UTC
**Name:** <Narvik_
<img width="1437" alt="Captura de Pantalla 2021-09-02 a la(s) 1 29 08 a m" src="https://user-images.githubusercontent.com/89964356/131794659-885dfe4d-bd1c-42c7-aadd-beb82b184c74.png">
Sanchez>
**Email:** <narvik27@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/narvik-s%C3%A1nchez/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1437" alt="Captura de Pantalla 2021-09-02 a la(s) 1 29 08 a m" src="https://user-images.githubusercontent.com/89964356/131794555-51fc7214-0d91-4cfb-9ca5-8f4547999c81.png">

**Comment by SonicDMG** [comment] 2021-09-02 20:41
Closing as a duplicate of https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/563

**Closed by SonicDMG** 2021-09-02 20:41 UTC
Labels: duplicate, wait for review, homework
