### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by PriyankaTadlagi** [datastaxdevs/workshop-introduction-to-nosql#333] opened 2021-07-29 11:47 UTC
**Name:** Priyanka Mallinath Tadlagi
**Email:** priyankatadlagi@gmail.cm
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot_2021_0729_163653](https://user-images.githubusercontent.com/88142912/127484589-ed98579d-0848-436c-a469-65a576659147.jpg)
![Screenshot_2021_0729_164033](https://user-images.githubusercontent.com/88142912/127484597-20f377e4-d935-492c-915c-dd3dbd848b26.jpg)
![Screenshot_20210728_142639](https://user-images.githubusercontent.com/88142912/127486571-ef21c6bd-f1dc-42d1-a13f-6915ae107c4f.jpg)
![Screenshot_20210728_154800](https://user-images.githubusercontent.com/88142912/127486593-8b34dfaa-c12d-4e17-8927-16424a518d36.jpg)
![Screenshot_20210728_144755](https://user-images.githubusercontent.com/88142912/127486608-7a5694a9-f16c-49e0-9e40-be5e28b19c0d.jpg)
![Screenshot_2021_0728_143116](https://user-images.githubusercontent.com/88142912/127486629-b4d3cc95-ce6f-4443-9225-67f50dda4ac9.jpg)

<SCREENSHOTS>

**Comment by SonicDMG** [comment] 2021-08-11 14:26
Duplicate of https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/332

**Closed by SonicDMG** 2021-08-11 14:26 UTC
Labels: duplicate, homework
